name: jeraflix_pelicom
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^2.0.0
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  carousel_slider: ^4.1.1
  google_fonts: ^3.0.1
  custom_refresh_indicator: ^2.0.1
  shimmer: ^2.0.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.17.0
  sqflite: ^2.2.2
  path: ^1.8.2
  mason: ^0.1.0-dev.47

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
